services:
    laravel-app:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.3/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${FORWARD_APP_PORT:-80}:80"
            - "${FORWARD_VITE_PORT:-5173}:5173"
            - '${REVERB_SERVER_PORT:-8080}:8080'
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - postgres
            - redis
            - mailpit
            - selenium
    postgres:
        image: "postgres:latest"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DATABASE_TEST: "${DB_DATABASE_TEST}"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        volumes:
            - "sail-postgres:/var/lib/postgresql/data"
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    selenium:
        image: "seleniarm/standalone-chromium"
        ports:
            - "${FORWARD_SELENIUM_PORT:-4444}:4444"
        environment:
            - START_XVFB=false
            - SE_NODE_OVERRIDE_MAX_SESSIONS=true
            - SE_NODE_MAX_SESSIONS=10
            - JAVA_OPTS=-XX:ActiveProcessorCount=10
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-nginx:
        driver: local
    sail-postgres:
        driver: local
    sail-redis:
        driver: local
